name: mrt_card_reader
description: Read balance and transaction history from Dhaka MRT Line 6 metro rail cards via NFC. Based on the MRT Buddy team's work.
version: 0.2.0
repository: https://github.com/ishafiul/mrt_reader_flutter
homepage: https://github.com/ishafiul/mrt_reader_flutter
issue_tracker: https://github.com/ishafiul/mrt_reader_flutter/issues

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  nfc_manager: ^4.1.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
